// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Sunrise.Shared.Database;

namespace Sunrise.Shared.Database.Migrations
{
    [DbContext(typeof(SunriseDbContext))]
    [Migration("20250821032507_AddClanJoinRequests")]
    partial class AddClanJoinRequests
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal for runtime; full model is defined in SunriseDbContextModelSnapshot
        }
    }
}


