name: osu-sunrise-dev
services:
  sunrise-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5149:443"  # HTTPS for development
      - "5150:80"   # HTTP for development
    volumes:
      - ./Data:/app/Data
      - ./Sunrise.Server/appsettings.Development.json:/app/appsettings.Development.json
      - ./certificate.pfx:/app/certificate.pfx
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificate.pfx
    # extra_hosts removed; using service name on shared docker network like production
    restart: unless-stopped
    depends_on:
      - redis-dev
      - mysql-sunrise-dev
      - postgres-dev


  redis-dev:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - "6380:6379"  # Changed from 6379 to avoid conflicts


  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.dev.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3030:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus


  postgres-dev:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hangfire
    ports:
      - "5433:5432"  # Changed from 5432 to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data


  mysql-sunrise-dev:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sunrise
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3309:3306"  # Changed from 3308 to use different port


volumes:
  mysql:
  redis:
  postgres_data:

networks:
  default:
    external: true
    name: sunrise-network
