name: osu-sunrise
services:
  sunrise:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5147:443"
      - "5148:80"
    volumes:
      - ./Data:/app/Data
      - ./Sunrise.Server/appsettings.Production.json:/app/appsettings.Production.json
      - ./certificate.pfx:/app/certificate.pfx
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certificate.pfx
    restart: unless-stopped
    depends_on:
      - redis
      - prometheus

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis:/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3060:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hangfire
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql-sunrise-db:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sunrise
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql:
  redis:
  postgres_data:

networks:
  default:
    external: true
    name: sunrise-network
